[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "featuremap"
authors = [{name = "Test", email = "uqachoo1@uq.edu.au"}]
dynamic = ["version", "description"]